name: "Update Flake Deps"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    outputs:
      nixos_configurations: ${{ steps.gen_nixos_configurations.outputs.nixos_configurations }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://kristian.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= kristian.cachix.org-1:I9DC4coD583Us0HFeCW6KiiXbk6uhlWfB2MPxjJiiUI=
          install_url: https://releases.nixos.org/nix/nix-2.25.0/install
      - name: Generate flake.json
        run: |
          nix flake show --json > flake.json
      - id: gen_nixos_configurations
        run: |
          nixos_configurations=$(jq -c '.nixosConfigurations | keys' < flake.json)
          echo "nixos_configurations=$nixos_configurations" >> $GITHUB_OUTPUT

  update_flake:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://kristian.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= kristian.cachix.org-1:I9DC4coD583Us0HFeCW6KiiXbk6uhlWfB2MPxjJiiUI=
          install_url: https://releases.nixos.org/nix/nix-2.25.0/install
      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: kristian
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Set up git
        run: |
          git config user.email "kristian@krined.no"
          git config user.name "KristianAN"
      - name: Update the flake
        run: nix flake update
      - name: Store flake.lock
        uses: actions/upload-artifact@v4
        with:
          name: flake_lock
          path: flake.lock

  build_flake:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    needs: [generate_matrix, update_flake]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        nixos_configuration: ${{ fromJson(needs.generate_matrix.outputs.nixos_configurations) }}
    steps:
      - name: Free diskspace
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /nix
          swap-size-mb: 8192
          root-reserve-mb: 4096
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-docker-images: true
      - name: Clean up additional space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://kristian.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= kristian.cachix.org-1:I9DC4coD583Us0HFeCW6KiiXbk6uhlWfB2MPxjJiiUI=
            max-jobs = 2
            cores = 2
            max-silent-time = 1800
          install_url: https://releases.nixos.org/nix/nix-2.25.0/install
      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: kristian
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Restore flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake_lock
      - name: Build with periodic GC
        run: |
          # Start periodic GC in the background
          (while true; do nix-collect-garbage -d; sleep 300; done) &
          GCPID=$!
          # Ensure it's killed when the script exits
          trap "kill $GCPID" EXIT

          # Build the configuration
          nix build .#nixosConfigurations.${{ matrix.nixos_configuration }}.config.system.build.toplevel --out-link result
      - name: Push to cachix properly
        run: |
          STORE_PATH=$(readlink -f result)
          echo "Pushing complete closure of $STORE_PATH to Cachix"
          
          # Count paths in closure
          PATH_COUNT=$(nix path-info -r $STORE_PATH | wc -l)
          echo "Closure contains $PATH_COUNT total paths"
          
          # Push the entire closure with all dependencies
          cachix push kristian $STORE_PATH

  check_flake:
    runs-on: ubuntu-latest
    needs: [update_flake]
    continue-on-error: true
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          extra_nix_config: |
            auto-optimise-store = true
            access-tokens = github.com=${{ secrets.TEST_TOKEN }}
            experimental-features = nix-command flakes
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://kristian.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= kristian.cachix.org-1:I9DC4coD583Us0HFeCW6KiiXbk6uhlWfB2MPxjJiiUI=
          install_url: https://releases.nixos.org/nix/nix-2.25.0/install
      - name: Set up cachix
        uses: cachix/cachix-action@master
        with:
          name: kristian
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Restore flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake_lock
      - name: Check flake
        run: nix flake check --keep-going

  push_update:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [update_flake, build_flake, check_flake]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.TEST_TOKEN }}"
      - name: Restore flake.lock
        uses: actions/download-artifact@v4
        with:
          name: flake_lock
      - name: Set up git
        run: |
          git config user.email "kristian@krined.no"
          git config user.name "KristianAN"
      - name: Create and merge PR
        run: |
          git switch -c updates-${{ github.run_id }}
          git commit -am "flake.lock: Update"
          git push -u origin updates-${{ github.run_id }}
          PR=$(gh pr create \
            --assignee KristianAN \
            --base main \
            --body "Automatic flake update on $(date -I)" \
            --fill \
            --label bot \
            --title "Auto update $(date -I)")
          gh pr merge $PR --merge --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
